fixed typo in workflow
fixed pattern matching

fixed typo

fixed typo

diff --git a/.github/workflows/build_runtimes.yml b/.github/workflows/build_runtimes.yml
--- a/.github/workflows/build_runtimes.yml
+++ b/.github/workflows/build_runtimes.yml
@@ -4,7 +4,7 @@ name: Build runtime image
 on:
   push:
     tags:
-      - 'runtime-.*_.*'
+      - runtime**
 
 jobs:
   build:
@@ -17,15 +17,15 @@ jobs:
         docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
     - name: Check if image exists
       run: |
-        echo "IMAGE_NAME=$(echo 'tercen/$GITHUB_REF_NAME' | sed 's/_/:/')"  >> $GITHUB_ENV
-        echo "IMAGE_MISSING=$(docker manifest inspect env.IMAGE_NAME > /dev/null ; echo $?)"  >> $GITHUB_ENV
-        echo "DIR_NAME=$(echo env.IMAGE_NAME | grep -o -P '(?<=tercen/).*(?=:)')"  >> $GITHUB_ENV
+        echo "IMAGE_NAME=$(echo "tercen/$GITHUB_REF_NAME" | sed 's/_/:/')"  >> $GITHUB_ENV
+        echo "IMAGE_MISSING=$(docker manifest inspect ${{ env.IMAGE_NAME }} > /dev/null ; echo $?)"  >> $GITHUB_ENV
+        echo "DIR_NAME=$(echo "${{ env.IMAGE_NAME }}"" | grep -o -P '(?<=tercen/).*(?=:)')"  >> $GITHUB_ENV
     - name: Build docker image
       # run only if image is missing (1) 
       if: env.IMAGE_MISSING == 1
       run: |
-        docker build -t env.IMAGE_NAME ./${{ env.DIR_NAME }}
+        docker build -t ${{ env.IMAGE_NAME }} ./${{ env.DIR_NAME }}
     - name: docker push
       if: env.IMAGE_MISSING == 1
       run: |
-        docker push env.IMAGE_NAME
+        docker push ${{ env.IMAGE_NAME }}
